### ISSUE TITLE
Section 5.1.1 lacks one command needed to allow setting port security

### ISSUE THREAD

**Issue by PaulSpaven** [benpiper/learn-cisco-network-administration-in-a-month-of-lunches#1]
Ben, GREAT book! It could not have come along at a better time for me. I'm totally new at the Cisco game, working on my home lab and aiming for CCNA soon. Your book is providing the lab exercises I need.

One note thus far:
Working through section 5.1.1, I could not get the port security settings to save on my 3750 switch. Then I found [(http://www.cisco.com/c/en/us/support/docs/switches/catalyst-3750-series-switches/72846-layer2-secftrs-catl3fixed.html)] and it showed that I needed:
`Cat3750(config-if)#switchport mode access`

Then, I was able to do the rest of the exercises in the chapter. You first mention `switchport mode access` in section 5.4.2. Perhaps an earlier mention would help?

Thanks for your time, and keep up the great work!

**Comment by benpiper** [comment]
Thanks, @PaulSpaven! I'm glad you're enjoying the book. I'll look into getting this changed.

**Comment by benpiper** [comment]
Added `switchport mode access` to the lab exercise. It should appear in the final version.
